# Generated by Django 3.2.9 on 2021-11-12 18:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('date_start', models.DateField(verbose_name='Дата начала работы')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('sum_salaries', models.IntegerField(verbose_name='Всего выплачено')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='children', to='app.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
