# Generated by Django 3.2.9 on 2021-11-15 18:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_worker_sum_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.worker'),
        ),
    ]
