# Generated by Django 3.2.9 on 2021-11-15 19:16

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_worker_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.worker'),
        ),
    ]
