# Generated by Django 3.2.9 on 2021-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_worker_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sum_salaries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего выплачено'),
        ),
    ]
